### ISSUE TITLE
translate article: io.js and a node.js Foundation

### ISSUE THREAD

**Issue by timaschew** [iojs/iojs-de#13]
https://medium.com/@iojs/io-js-and-a-node-js-foundation-4e14699fb7be

First of all: what do we want to translate, everything on [medium by iojs](https://medium.com/@iojs)?

**Comment by fhemberger** [comment]
Hmm, depends on the willingness of the volunteers to do so. But this for example is an important article, so I'd say its of interest to the German community.

In the [website repo](https://github.com/iojs/website/issues/125#issuecomment-73783176) people are already requesting access to the original markdown files for the translation teams (instead of manually editing the markup of the rendered medium.com post).

**Comment by parroit** [comment]
:+1:  this. I'm trying to get the [list of markdown sources for the articles here](https://github.com/iojs/iojs-it/issues/14) but I'm not sure where to get latest version, and I don't found markdown for `io.js and a node.js Foundation`

**Comment by fhemberger** [comment]
I'm closing this for now because of the upcoming `new.nodejs.org` website.
